### PR TITLE
[DNM] first pass for sites and old-followers

### PR DESCRIPTION
**Pull request by ManushiM**
Implemented:

* Old method of `initiative1.followers()`
* `myHub.initiatives.add(title)` creates initiative site, protects it from deletion, adds it collab group and sets it as initiative url
*`myHub.sites.add(title,domain,group_id)` creates OD group with `group_id` as group
* `myHub.sites.get(id)`
* `myHub.sites.search()`

### CODE REVIEW

**Comment by ajturner** [comment]
Why did you choose `add()` instead of `create()` for initiatives & sites? 

To me, _add_ means "something that already exists and add it to a collection" vs `create` means "make a new thing"

**Comment by ajturner** [comment]
Can you please add an example to a Markdown file (_e.g._ Readme or another examples.md) or a notebook to provide a simple demonstration of how the Site module is used

**Comment by ManushiM** [comment]
> 
> 
> Why did you choose `add()` instead of `create()` for initiatives & sites?
> 
> To me, _add_ means "something that already exists and add it to a collection" vs `create` means "make a new thing"

Uniformity with `arcgis` https://esri.github.io/arcgis-python-api/apidoc/html/arcgis.gis.toc.html#arcgis.gis.ContentManager.add

**Comment by ManushiM** [comment]
> 
> 
> Can you please add an example to a Markdown file (_e.g._ Readme or another examples.md) or a notebook to provide a simple demonstration of how the Site module is used

Yes, I'm working on an example notebook. It's just very sparse currently. Will add it after I implement more methods (`update()` and `delete()` at least)

**Comment by ajturner** [comment]
can you get this PR up-to-date and merge?

**Pull request merged**
